# Generated by Django 2.1.2 on 2018-10-28 20:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_to_movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
