# Generated by Django 2.1.2 on 2018-10-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_to_movie', '0002_movierecommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodtomovie',
            name='analytical',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodtomovie',
            name='anger',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodtomovie',
            name='confident',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodtomovie',
            name='fear',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodtomovie',
            name='genre_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodtomovie',
            name='joy',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodtomovie',
            name='sadness',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodtomovie',
            name='tentative',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
