# Generated by Django 2.1.2 on 2018-10-28 21:44

from django.db import migrations
from django.core.management import call_command

def initial_data(apps, schema_editor):
    call_command('loaddata', 'initial_data.json')



class Migration(migrations.Migration):

    dependencies = [
        ('mood_to_movie', '0003_auto_20181028_1737'),
    ]

    operations = [
        migrations.RunPython(initial_data),
    ]


