# Generated by Django 2.1.2 on 2018-11-01 20:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_to_movie', '0004_auto_20181028_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='FBMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_username', models.CharField(max_length=50)),
                ('messages', django.contrib.postgres.fields.jsonb.JSONField()),
                ('anger', models.FloatField()),
                ('fear', models.FloatField()),
                ('joy', models.FloatField()),
                ('sadness', models.FloatField()),
                ('analytical', models.FloatField()),
                ('confident', models.FloatField()),
                ('tentative', models.FloatField()),
            ],
        ),
    ]
