# Generated by Django 2.1.3 on 2018-12-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood_to_movie', '0005_fbmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FBMessages',
            new_name='TwitterMessages',
        ),
    ]
